export default {
  props: [{
    name: 'icon',
    type: 'String',
    default: '',
    desc: 'props.icon'
  }, {
    name: 'iconClass',
    type: 'String,Object,Array',
    default: '',
    desc: 'props.iconClass'
  }, {
    name: 'menuClass',
    type: 'String,Object,Array',
    default: '',
    desc: 'props.menuClass'
  }, {
    name: 'menuListClass',
    type: 'String,Object,Array',
    default: '',
    desc: 'props.menuListClass'
  }, {
    name: 'multiple',
    type: 'Boolean',
    default: 'false',
    desc: 'props.multiple'
  }, {
    name: 'desktop',
    type: 'Boolean',
    default: 'false',
    desc: 'props.desktop'
  }, {
    name: 'maxHeight',
    type: 'Number',
    default: '',
    desc: 'props.maxHeight'
  }, {
    name: 'open',
    type: 'Boolean',
    default: 'false',
    desc: 'props.open'
  }, {
    name: 'itemClickClose',
    type: 'Boolean',
    default: 'true',
    desc: 'props.itemClickClose'
  }, {
    name: 'anchorOrigin',
    type: 'Object',
    default: '{vertical: \'top\',horizontal: \'left\'}',
    desc: 'props.anchorOrigin'
  }, {
    name: 'targetOrigin',
    type: 'Object',
    default: '{vertical: \'top\',horizontal: \'left\'}',
    desc: 'props.targetOrigin'
  }, {
    name: 'scroller',
    type: 'Element',
    default: 'window',
    desc: 'props.scroller'
  }, {
    name: 'tooltip',
    type: 'String',
    default: '',
    desc: 'props.tooltip'
  }, {
    name: 'tooltipPosition',
    type: 'String',
    default: 'bottom-center',
    desc: 'props.tooltipPosition'
  }, {
    name: 'value',
    type: '',
    default: '',
    desc: 'props.value'
  }],
  slots: [{
    name: 'icon',
    desc: 'slots.icon'
  }, {
    name: 'default',
    desc: 'slots.default'
  }],
  events: [{
    name: 'itemClick',
    desc: 'events.itemClick'
  }, {
    name: 'change',
    desc: 'events.change'
  }, {
    name: 'open',
    desc: 'events.open'
  }, {
    name: 'close',
    desc: 'events.close'
  }]
}
