export default {
  props: [{
    name: 'autoWidth',
    type: 'Boolean',
    default: 'false',
    desc: 'props.autoWidth'
  }, {
    name: 'maxHeight',
    type: 'Number',
    default: '',
    desc: 'props.maxHeight'
  }, {
    name: 'multiple',
    type: 'Boolean',
    default: 'false',
    desc: 'props.multiple'
  }, {
    name: 'disabled',
    type: 'Boolean',
    default: 'false',
    desc: 'props.disabled'
  }, {
    name: 'openImmediately',
    type: 'Boolean',
    default: 'false',
    desc: 'props.openImmediately'
  }, {
    name: 'anchorOrigin',
    type: 'Object',
    default: '{vertical: \'top\', horizontal: \'left\'}',
    desc: 'props.anchorOrigin'
  }, {
    name: 'scroller',
    type: 'Element',
    default: 'window',
    desc: 'props.scroller'
  }, {
    name: 'labelClass',
    type: 'String,Object,Array',
    default: '',
    desc: 'props.labelClass'
  }, {
    name: 'iconClass',
    type: 'String,Object,Array',
    default: '',
    desc: 'props.iconClass'
  }, {
    name: 'menuClass',
    type: 'String,Object,Array',
    default: '',
    desc: 'props.menuClass'
  }, {
    name: 'menuListClass',
    type: 'String,Object,Array',
    default: '',
    desc: 'props.menuListClass'
  }, {
    name: 'underlineClass',
    type: 'String,Object,Array',
    default: '',
    desc: 'props.underlineClass'
  }],
  slots: [{
    name: 'default',
    desc: 'slots.default'
  }],
  events: [{
    name: 'change',
    desc: 'events.change'
  }, {
    name: 'open',
    desc: 'events.open'
  }, {
    name: 'close',
    desc: 'events.close'
  }]
}
