export default [{
  name: 'to',
  type: 'String,Object',
  default: '',
  desc: 'router.to'
}, {
  name: 'tag',
  type: 'String',
  default: 'a',
  desc: 'router.tag'
}, {
  name: 'activeClass',
  type: 'String',
  default: 'router-link-active',
  desc: 'router.activeClass'
}, {
  name: 'event',
  type: 'String,Array',
  default: 'click',
  desc: 'router.event'
}, {
  name: 'exact',
  type: 'Boolean',
  default: '',
  desc: 'router.exact'
}, {
  name: 'append',
  type: 'Boolean',
  default: '',
  desc: 'router.append'
}, {
  name: 'replace',
  type: 'Boolean',
  default: '',
  desc: 'router.replace'
}]
